### PR TITLE
OCaml version to 4.14

### LINKED ISSUE #56: libASL: broken build
The latest version on the `partial_eval` branch appears to be broken:

```
> dune exec asli
File "libASL/ocaml_backend.ml", line 35, characters 2-18:
35 |   String.fold_left (fun acc c ->
       ^^^^^^^^^^^^^^^^
Error: Unbound value String.fold_left
File "libASL/offline_transform.ml", line 30, characters 12-24:
30 |     let s = List.compare compare_taint la lb in
                 ^^^^^^^^^^^^
Error: Unbound value List.compare
Hint: Did you mean combine?
File "libASL/req_analysis.ml", line 55, characters 56-64:
55 | type 'a wrm = (state -> (state * stmt list * 'a,string) Either.t)
                                                             ^^^^^^^^
Error: Unbound module Either
```

The same errors appear in CI builds:
https://github.com/UQ-PAC/aslp/actions/runs/8321443436/job/22767695809

### PR DESCRIPTION
**Pull request by ncough**
Fix up build issues introduced by #55 by bumping OCaml version up to 4.14.

### CODE REVIEW

**Comment by katrinafyi** [comment]
Thanks! Also: https://github.com/UQ-PAC/aslp/blob/partial_eval/.github/workflows/opam.yml
