### ISSUE TITLE
libASL: broken build

### ISSUE THREAD

**Issue by mmcloughlin** [UQ-PAC/asl-interpreter#56]
The latest version on the `partial_eval` branch appears to be broken:

```
> dune exec asli
File "libASL/ocaml_backend.ml", line 35, characters 2-18:
35 |   String.fold_left (fun acc c ->
       ^^^^^^^^^^^^^^^^
Error: Unbound value String.fold_left
File "libASL/offline_transform.ml", line 30, characters 12-24:
30 |     let s = List.compare compare_taint la lb in
                 ^^^^^^^^^^^^
Error: Unbound value List.compare
Hint: Did you mean combine?
File "libASL/req_analysis.ml", line 55, characters 56-64:
55 | type 'a wrm = (state -> (state * stmt list * 'a,string) Either.t)
                                                             ^^^^^^^^
Error: Unbound module Either
```

The same errors appear in CI builds:
https://github.com/UQ-PAC/aslp/actions/runs/8321443436/job/22767695809

**Comment by katrinafyi** [comment]
The latest changes (#55) have broken backwards-compatibility with OCaml 4.09. The Nix-based CI uses OCaml 4.14 and this version of should work. 

@ncough Is there an interest in supporting older OCaml? If so, we can use a stdlib supplement like [containers](https://c-cube.github.io/ocaml-containers/last/containers/index.html). Otherwise, we can simply update the documentation and CI.

**Comment by ncough** [comment]
I am not aware of any need to remain at 4.09. The BAP plugin should continue to work with 4.14.

**Comment by mmcloughlin** [comment]
Thanks! Confirmed works fine upon upgrading to 4.14.
